name: android

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install dependencies
        run: |
          npm install -g yarn
          yarn
      - name: generate app.json
        run: yarn make-app-json
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: "expo build:android -t app-bundle"
        shell: bash
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
      - run: 'echo "$GOOGLE_API_KEY" > key.json'
        shell: bash
        env:
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
      - run: expo upload:android --latest --key key.json --use-submission-service
