name: pr

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  publish_for_testing:
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: |
      github.ref != 'refs/heads/main' &&
      !startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: ./.github/actions/prepare
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{secrets.EXPO_CLI_USERNAME}}
          expo-password: ${{secrets.EXPO_CLI_PASSWORD}}
      - run: 'echo "$GOOGLE_SERVICES_JSON" > google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
      - run: "expo publish --release-channel $(echo ${GITHUB_REF} | tr / -)"
        shell: bash
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}

  comment_with_links_for_testing:
    runs-on: ubuntu-latest
    needs: publish_for_testing
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, ref  } = context;
            const channel = ref.replace(/[/]/g, '-');
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: `Test version url: https://expo.io/@nvbn/projects/curfew-alarm?release-channel=${channel}&sdkVersion=40.0.0`
            });
