name: pr

on:
  pull_request:
#    types: [opened, reopened]

jobs:
  comment_with_links_for_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, ref  } = context;
            const channel = ref.replace('refs/heads/', '').replaceAll('/', '-');
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: `Test version url: https://expo.io/@nvbn/projects/curfew-alarm?release-channel=${channel}&sdkVersion=40.0.0`
            });
